#!/usr/bin/env zsh

## hyprland
echo "\nhyprland"
rsync -a --delete ~/personal/.config/hypr/ ~/.config/hypr/
#rm -r ~/.config/hypr/*
#cp -r ~/personal/.config/hypr/* ~/.config/hypr/
ls -a ~/.config/hypr/
hyprctl reload

## wezterm
echo "\nwezterm"
rsync -a --delete ~/personal/.config/wezterm/ ~/.config/wezterm/
ls -a ~/.config/wezterm/

## zsh
echo "\nzsh"
CUSTOM="$HOME/.oh-my-zsh/custom/aliases.zsh"
rsync -a --delete ~/personal/.config/zsh/aliases.zsh "$CUSTOM"
rsync -a --delete ~/personal/.config/zsh/.zshrc "$HOME/.zshrc"
source ~/.zshrc
#ls -a $ZSH_CUSTOM/
tail "$CUSTOM"

## keyd
#echo "\nkeyd"   
#sudo rsync -a --delete ~/personal/.config/keyd/default.conf /etc/keyd/default.conf
#sudo systemctl enable --now keyd
#sudo keyd reload
#tail "/etc/keyd/default.conf"
