# ── TPM Plugin Manager ───────────────────
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'rose-pine/tmux'

# ── Prefix Key ──────────────────────────
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# ── General Settings ─────────────────────
set -g mouse on
set-window-option -g mode-keys vi
set -g history-limit 10000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# ── Status Bar ────────────────────────────
set -g status-position bottom
set -g status-interval 5
set -g status-left " #S "
set -g status-right " %H:%M %d-%b "

# ── Terminal Colors ──────────────────────
# set -g default-terminal "tmux-256color"
# set -ga terminal-overrides ",*256col*:Tc"


# Theme
set -g @rose_pine_variant 'moon'
set -g @rose_pine_directory 'on' # Turn on the current folder component in the status bar
set -g @rose_pine_bar_bg_disable 'on' # Disables background color, for transparent terminal emulators
set -g @rose_pine_bar_bg_disabled_color_option 'default'
set -g @rose_pine_session_icon '' # Changes the default icon to the left of the session name
set -g @rose_pine_current_window_icon '' # Changes the default icon to the left of the active window name
set -g @rose_pine_folder_icon '' # Changes the default icon to the left of the current directory folder

set -g @plugin 'tmux-plugins/tpm'
run "$HOME/.config/tmux/plugins/tpm/tpm"
