# TPM Plugin Manager 
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'rose-pine/tmux'

# remap
set-option -g prefix C-b
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'

bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# ── General Settings ─────────────────────
set -g mouse on
set -g history-limit 10000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Theme
set -g @rose_pine_variant 'moon'
set -g @rose_pine_directory 'on' # Turn on the current folder component in the status bar
set -g @rose_pine_bar_bg_disable 'on' # Disables background color, for transparent terminal emulators
set -g @rose_pine_bar_bg_disabled_color_option 'default'
set -g @rose_pine_session_icon '' # Changes the default icon to the left of the session name
set -g @rose_pine_current_window_icon '' # Changes the default icon to the left of the active window name
set -g @rose_pine_folder_icon '' # Changes the default icon to the left of the current directory folder

set -g @plugin 'tmux-plugins/tpm'
run "$HOME/.config/tmux/plugins/tpm/tpm"
